name: rhaco
channels:
- glotzer
- cmelab
- mosdef
- omnia
- defaults
dependencies:
- python=3.5.3
- hoomd_dybond
- mbuild=0.8.0
- foyer=0.4.0
- scipy=0.19.1
- matplotlib=2.0.2
- freud
- signac=0.9.2
- signac-flow
- gsd=1.5.2
- cython
