name: lynx
channels:
- glotzer
- cmelab
- mosdef
- omnia
- defaults
dependencies:
- python=3.5
- hoomd_dybond
- mbuild=0.8.0
- scipy=0.19.1
- matplotlib=2.0.2
- freud=0.8.0
- signac=0.9.2
- signac-flow=0.5.6
- gsd=1.5.2
